### ISSUE TITLE
How to search joined column?

### ISSUE THREAD

**Issue by tsulatsitamim** [Obapelumi/adosearch#3]

**Comment by Obapelumi** [comment]
Hi @tsulatsitamim could you please provide a detailed description of what you are trying to do?

**Comment by tsulatsitamim** [comment]
I've query 

```
const services = await Service
  .query()
  .join('categories', 'categories.id', 'services.category_id')
  .select('services.*', 'categories.name as category_name')
```

I want to include category_name in search

**Comment by Obapelumi** [comment]
You can create a `Category` model for the categories table, add it as an association on the `Service` model and then add `categories.name` as a searchable column on the `Service` model. For example:

```ts
import { search } from 'adosearch'

class Category extends BaseModel {
  @column()
  name: string
}

class Service extends BaseModel {
  @hasMany(() => Category)
  categories: HasMany<typeof Category>

  static search = search(this, ['categories.name'])
}
```

Hope this helps

**Comment by tsulatsitamim** [comment]
I'v datatable on front end, which will sort the column key, if I use categories.name as column key, the sort will not work.

**Comment by Obapelumi** [comment]
Not sure what you setup looks like but I think this is out of the scope of this package so I'll be closing this issue.
